### PR TITLE
refactor: Updated ru.ts and en.ts.

### PR DESCRIPTION
**Pull request by MrEvgeniy1989**

### CODE REVIEW

**Review by Commonaccount2024 — APPROVED** [review]

**Comment by Commonaccount2024** [comment]
run build production

**Comment by MrEvgeniy1989** [comment]
run build production

**Comment by Commonaccount2024** [comment]
run build production

**Comment by Commonaccount2024** [comment]
run build production

**Comment by MrEvgeniy1989** [comment]
run build production

**Pull request merged**
